/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import javax.swing.JOptionPane;
import modules.LibraryManagement;
import modules.LibraryServices;
import modules.interfacesmodules.IBook;
import modules.interfacesmodules.ILibraryServices;

/**
 *
 * @author Rosbel
 */
public class PantallaFuncional extends javax.swing.JFrame {
        
        private ILibraryServices services;
        private LibraryManagement libraryManagement;
    

    /**
     * Creates new form paginaFuncional
     */
    public PantallaFuncional() {
        initComponents();
         services = new LibraryServices();
         libraryManagement = new LibraryManagement(services);
          this.setLocationRelativeTo(null);
    }
    
    public PantallaFuncional(LibraryManagement libraryManagement){
        initComponents();
        this.libraryManagement = libraryManagement;
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        BookManagementScreen = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        LoanManagementScreen = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        botonBuscarTitulo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        barraDeBusqueda = new javax.swing.JProgressBar();
        findTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonBuscarAutor = new javax.swing.JButton();
        botonBuscarID = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema-de-Prestamos-para-una-Biblioteca");
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setToolTipText("Buscar Libro");

        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        jSeparator10.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.add(jSeparator10);

        BookManagementScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazGrafica/imagen/Add.png"))); // NOI18N
        BookManagementScreen.setText("Books");
        BookManagementScreen.setFocusable(false);
        BookManagementScreen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BookManagementScreen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BookManagementScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookManagementScreenActionPerformed(evt);
            }
        });
        jToolBar1.add(BookManagementScreen);

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.add(jSeparator7);

        LoanManagementScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazGrafica/imagen/prestado.png"))); // NOI18N
        LoanManagementScreen.setText("Registros");
        LoanManagementScreen.setFocusable(false);
        LoanManagementScreen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoanManagementScreen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LoanManagementScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanManagementScreenActionPerformed(evt);
            }
        });
        jToolBar1.add(LoanManagementScreen);

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.add(jSeparator8);

        botonBuscarTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonBuscarTitulo.setText("Buscar por Titulo");
        botonBuscarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarTituloActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Buscar Libro:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazGrafica/imagen/logo.png"))); // NOI18N

        botonBuscarAutor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonBuscarAutor.setText("Buscar por Autor");
        botonBuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarAutorActionPerformed(evt);
            }
        });

        botonBuscarID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonBuscarID.setText("Buscar por ID");
        botonBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarIDActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonBuscarTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(barraDeBusqueda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(findTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonBuscarAutor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonBuscarID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(barraDeBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(botonBuscarAutor)
                        .addGap(18, 18, 18)
                        .addComponent(botonBuscarTitulo)
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(botonBuscarID)
                                .addGap(0, 98, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(findTextField)
                        .addGap(109, 109, 109)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(findTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarAutor)
                    .addComponent(botonBuscarTitulo)
                    .addComponent(botonBuscarID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(barraDeBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookManagementScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookManagementScreenActionPerformed
        // TODO add your handling code here:
    BookManagementScreen addBookForm = new BookManagementScreen (libraryManagement);
        addBookForm.setVisible(true);
    }//GEN-LAST:event_BookManagementScreenActionPerformed

    private void botonBuscarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarTituloActionPerformed
        // TODO add your handling code here:
        IBook book = libraryManagement.findByTitle(getTextField());
        if (book != null){
            InfoBook form = new InfoBook(libraryManagement, book);
            form.setVisible(true);
        }else {
            JOptionPane.showMessageDialog(null, "Libro no encontrado");
        }
    }//GEN-LAST:event_botonBuscarTituloActionPerformed

    private void LoanManagementScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanManagementScreenActionPerformed
        // TODO add your handling code here:
         LoanManagementScreen prestados = new LoanManagementScreen(libraryManagement);
        prestados.setVisible(true);
    }//GEN-LAST:event_LoanManagementScreenActionPerformed

    private void botonBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarAutorActionPerformed
        // TODO add your handling code here:
        if (findTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene el campo");
        } else{
        if (!findTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene el campo");
        } else{
            IBook book = libraryManagement.findByAuthor(getTextField());
            if (book != null){
                InfoBook form = new InfoBook(libraryManagement, book);
                form.setVisible(true);
            }else {
                JOptionPane.showMessageDialog(null, "Libro no encontrado");
        } 
        }
        }

        // Aqui abres pantalla para preguntar si editar o borrar
    }//GEN-LAST:event_botonBuscarAutorActionPerformed

    private String getTextField(){
        return findTextField.getText();
    }
    
    private void botonBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarIDActionPerformed
        // TODO add your handling code here:4
        if (findTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene el campo");
        } else{
        IBook book = libraryManagement.findByID(getTextField());
        if (book != null){
            InfoBook form = new InfoBook(libraryManagement, book);
            form.setVisible(true);
        }else {
            JOptionPane.showMessageDialog(null, "Libro no encontrado");
        }
        }
    }//GEN-LAST:event_botonBuscarIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PantallaFuncional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookManagementScreen;
    private javax.swing.JButton LoanManagementScreen;
    private javax.swing.JProgressBar barraDeBusqueda;
    private javax.swing.JButton botonBuscarAutor;
    private javax.swing.JButton botonBuscarID;
    private javax.swing.JButton botonBuscarTitulo;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JTextField findTextField;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
